/* Generated by Pyrex 0.9.4.1 on Tue Dec 19 14:23:05 2006 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "event.h"
#include "evmsg.h"


typedef struct {const char *s; const void **p;} __Pyx_CApiTabEntry; /*proto*/
typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_EndUnpack(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], Py_ssize_t nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static int __Pyx_InitCApi(PyObject *module); /*proto*/
static int __Pyx_ImportModuleCApi(__Pyx_CApiTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from evmsg */


struct __pyx_obj_5evmsg_subscribe {
  PyObject_HEAD
  void (*handle);
  PyObject *callback;
  PyObject *args;
};

static PyTypeObject *__pyx_ptype_5evmsg_subscribe = 0;
static PyObject *__pyx_k1;
static PyObject *__pyx_k2;
static PyObject *__pyx_k3;
static void (__pyx_f_5evmsg___subscribe_cb(char (*),char (*),char (*),struct evbuffer (*),void (*))); /*proto*/

/* Implementation of evmsg */

static PyObject *__pyx_n_EVMSG_DEFAULT_PORT;
static PyObject *__pyx_n_EVMSG_DEFAULT_SSL_PORT;
static PyObject *__pyx_n_open;
static PyObject *__pyx_n_set_auth;
static PyObject *__pyx_n_publish;
static PyObject *__pyx_n_close;
static PyObject *__pyx_n_False;

static PyObject *__pyx_n_callback;
static PyObject *__pyx_n_args;

static void __pyx_f_5evmsg___subscribe_cb(char (*__pyx_v_channel),char (*__pyx_v_type),char (*__pyx_v_sender),struct evbuffer (*__pyx_v_buf),void (*__pyx_v_arg)) {
  PyObject *__pyx_v_sub;
  PyObject *__pyx_v_s;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  __pyx_v_sub = Py_None; Py_INCREF(Py_None);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":35 */
  __pyx_1 = (PyObject *)__pyx_v_arg;
  Py_INCREF(__pyx_1);
  Py_DECREF(__pyx_v_sub);
  __pyx_v_sub = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":36 */
  __pyx_2 = (__pyx_v_sender == 0);
  if (__pyx_2) {

    /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":37 */
    Py_INCREF(Py_None);
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = Py_None;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":39 */
    __pyx_1 = PyString_FromString(__pyx_v_sender); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = __pyx_1;
    __pyx_1 = 0;
  }
  __pyx_L2:;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":40 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_sub, __pyx_n_callback); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_3 = PyString_FromString(__pyx_v_channel); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_4 = PyString_FromString(__pyx_v_type); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_5 = PyBuffer_FromMemory(EVBUFFER_DATA(__pyx_v_buf),EVBUFFER_LENGTH(__pyx_v_buf)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
  Py_INCREF(__pyx_v_s);
  PyTuple_SET_ITEM(__pyx_6, 2, __pyx_v_s);
  PyTuple_SET_ITEM(__pyx_6, 3, __pyx_5);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_3 = PyObject_GetAttr(__pyx_v_sub, __pyx_n_args); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_4 = PySequence_Tuple(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyNumber_Add(__pyx_6, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_WriteUnraisable("evmsg.__subscribe_cb");
  __pyx_L0:;
  Py_DECREF(__pyx_v_sub);
  Py_DECREF(__pyx_v_s);
}

static PyObject *__pyx_n_EVMSG_DEFAULT_PORT_SSL;

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "127.0.0.1";

static PyObject *__pyx_f_5evmsg_open(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5evmsg_open[] = "Open our msgbus connection.";
static PyObject *__pyx_f_5evmsg_open(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_server = 0;
  PyObject *__pyx_v_port = 0;
  PyObject *__pyx_v_use_ssl = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  char (*__pyx_3);
  unsigned short __pyx_4;
  static char *__pyx_argnames[] = {"server","port","use_ssl",0};
  __pyx_v_server = __pyx_k1;
  __pyx_v_port = __pyx_k2;
  __pyx_v_use_ssl = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_server, &__pyx_v_port, &__pyx_v_use_ssl)) return 0;
  Py_INCREF(__pyx_v_server);
  Py_INCREF(__pyx_v_port);
  Py_INCREF(__pyx_v_use_ssl);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":46 */
  __pyx_1 = __pyx_v_server == Py_None;
  if (__pyx_1) {

    /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":47 */
    Py_INCREF(__pyx_k4p);
    Py_DECREF(__pyx_v_server);
    __pyx_v_server = __pyx_k4p;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":48 */
  __pyx_1 = __pyx_v_port == Py_None;
  if (__pyx_1) {

    /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":49 */
    __pyx_1 = PyObject_IsTrue(__pyx_v_use_ssl); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    if (__pyx_1) {

      /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":50 */
      __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_EVMSG_DEFAULT_PORT_SSL); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
      Py_DECREF(__pyx_v_port);
      __pyx_v_port = __pyx_2;
      __pyx_2 = 0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":52 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_EVMSG_DEFAULT_PORT); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
      Py_DECREF(__pyx_v_port);
      __pyx_v_port = __pyx_2;
      __pyx_2 = 0;
    }
    __pyx_L4:;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":53 */
  __pyx_3 = PyString_AsString(__pyx_v_server); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  __pyx_4 = PyInt_AsLong(__pyx_v_port); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  __pyx_1 = PyInt_AsLong(__pyx_v_use_ssl); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  evmsg_open(__pyx_3,__pyx_4,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("evmsg.open");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_server);
  Py_DECREF(__pyx_v_port);
  Py_DECREF(__pyx_v_use_ssl);
  return __pyx_r;
}

static PyObject *__pyx_f_5evmsg_set_auth(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5evmsg_set_auth[] = "Set a username and password to connect with.";
static PyObject *__pyx_f_5evmsg_set_auth(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_username = 0;
  PyObject *__pyx_v_password = 0;
  PyObject *__pyx_r;
  char (*__pyx_1);
  char (*__pyx_2);
  static char *__pyx_argnames[] = {"username","password",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_username, &__pyx_v_password)) return 0;
  Py_INCREF(__pyx_v_username);
  Py_INCREF(__pyx_v_password);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":57 */
  __pyx_1 = PyString_AsString(__pyx_v_username); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_password); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  evmsg_set_auth(__pyx_1,__pyx_2);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("evmsg.set_auth");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_username);
  Py_DECREF(__pyx_v_password);
  return __pyx_r;
}

static PyObject *__pyx_n_len;

static PyObject *__pyx_f_5evmsg_publish(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5evmsg_publish[] = "Publish a message.";
static PyObject *__pyx_f_5evmsg_publish(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_channel = 0;
  PyObject *__pyx_v_type = 0;
  PyObject *__pyx_v_msg = 0;
  struct evbuffer (*__pyx_v_buf);
  PyObject *__pyx_r;
  char (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  char (*__pyx_6);
  static char *__pyx_argnames[] = {"channel","type","msg",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_channel, &__pyx_v_type, &__pyx_v_msg)) return 0;
  Py_INCREF(__pyx_v_channel);
  Py_INCREF(__pyx_v_type);
  Py_INCREF(__pyx_v_msg);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":62 */
  __pyx_v_buf = evbuffer_new();

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":63 */
  __pyx_1 = PyString_AsString(__pyx_v_msg); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_INCREF(__pyx_v_msg);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_msg);
  __pyx_4 = PyObject_Call(__pyx_2, __pyx_3, 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  evbuffer_add(__pyx_v_buf,__pyx_1,__pyx_5);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":64 */
  __pyx_1 = PyString_AsString(__pyx_v_channel); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  __pyx_6 = PyString_AsString(__pyx_v_type); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
  evmsg_publish(__pyx_1,__pyx_6,__pyx_v_buf);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("evmsg.publish");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_channel);
  Py_DECREF(__pyx_v_type);
  Py_DECREF(__pyx_v_msg);
  return __pyx_r;
}

static PyObject *__pyx_n_SUB;


static int __pyx_f_5evmsg_9subscribe___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5evmsg_9subscribe___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_channel = 0;
  PyObject *__pyx_v_type = 0;
  PyObject *__pyx_v_sender = 0;
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_args = 0;
  int __pyx_r;
  char (*__pyx_1);
  char (*__pyx_2);
  char (*__pyx_3);
  static char *__pyx_argnames[] = {"channel","type","sender","callback",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 4, &__pyx_v_args, 0) < 0) return -1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_channel, &__pyx_v_type, &__pyx_v_sender, &__pyx_v_callback)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return -1;
  }
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_channel);
  Py_INCREF(__pyx_v_type);
  Py_INCREF(__pyx_v_sender);
  Py_INCREF(__pyx_v_callback);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":84 */
  Py_INCREF(__pyx_v_callback);
  Py_DECREF(((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->callback);
  ((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->callback = __pyx_v_callback;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":85 */
  Py_INCREF(__pyx_v_args);
  Py_DECREF(((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->args);
  ((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->args = __pyx_v_args;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":86 */
  __pyx_1 = PyString_AsString(__pyx_v_channel); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_2 = PyString_AsString(__pyx_v_type); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_3 = PyString_AsString(__pyx_v_sender); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  ((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->handle = evmsg_subscribe(__pyx_1,__pyx_2,__pyx_3,__pyx_f_5evmsg___subscribe_cb,((void (*))__pyx_v_self));

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":88 */
  if (__Pyx_PrintItem(__pyx_n_SUB) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("evmsg.subscribe.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_channel);
  Py_DECREF(__pyx_v_type);
  Py_DECREF(__pyx_v_sender);
  Py_DECREF(__pyx_v_callback);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_n_UNSUB;


static void __pyx_f_5evmsg_9subscribe___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_5evmsg_9subscribe___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":91 */
  if (__Pyx_PrintItem(__pyx_n_UNSUB) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":92 */
  evmsg_unsubscribe(((struct __pyx_obj_5evmsg_subscribe *)__pyx_v_self)->handle);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("evmsg.subscribe.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_5evmsg_close(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5evmsg_close[] = "Close our msgbus connection.";
static PyObject *__pyx_f_5evmsg_close(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":96 */
  evmsg_close();

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("evmsg.close");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_EVMSG_DEFAULT_PORT, "EVMSG_DEFAULT_PORT"},
  {&__pyx_n_EVMSG_DEFAULT_PORT_SSL, "EVMSG_DEFAULT_PORT_SSL"},
  {&__pyx_n_EVMSG_DEFAULT_SSL_PORT, "EVMSG_DEFAULT_SSL_PORT"},
  {&__pyx_n_False, "False"},
  {&__pyx_n_SUB, "SUB"},
  {&__pyx_n_UNSUB, "UNSUB"},
  {&__pyx_n_args, "args"},
  {&__pyx_n_callback, "callback"},
  {&__pyx_n_close, "close"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_open, "open"},
  {&__pyx_n_publish, "publish"},
  {&__pyx_n_set_auth, "set_auth"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_5evmsg_subscribe(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5evmsg_subscribe *p = (struct __pyx_obj_5evmsg_subscribe *)o;
  p->callback = Py_None; Py_INCREF(Py_None);
  p->args = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_5evmsg_subscribe(PyObject *o) {
  struct __pyx_obj_5evmsg_subscribe *p = (struct __pyx_obj_5evmsg_subscribe *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_5evmsg_9subscribe___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->callback);
  Py_XDECREF(p->args);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5evmsg_subscribe(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5evmsg_subscribe *p = (struct __pyx_obj_5evmsg_subscribe *)o;
  if (p->callback) {
    e = (*v)(p->callback, a); if (e) return e;
  }
  if (p->args) {
    e = (*v)(p->args, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_5evmsg_subscribe(PyObject *o) {
  struct __pyx_obj_5evmsg_subscribe *p = (struct __pyx_obj_5evmsg_subscribe *)o;
  Py_XDECREF(p->callback);
  p->callback = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->args);
  p->args = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_5evmsg_subscribe[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_5evmsg_subscribe[] = {
  {"callback", T_OBJECT, offsetof(struct __pyx_obj_5evmsg_subscribe, callback), 0, 0},
  {"args", T_OBJECT, offsetof(struct __pyx_obj_5evmsg_subscribe, args), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_subscribe = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_subscribe = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_subscribe = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_subscribe = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_5evmsg_subscribe = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "evmsg.subscribe", /*tp_name*/
  sizeof(struct __pyx_obj_5evmsg_subscribe), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5evmsg_subscribe, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_subscribe, /*tp_as_number*/
  &__pyx_tp_as_sequence_subscribe, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_subscribe, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_subscribe, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "subscribe(channel, type, sender, callback, *args) -> sub object\n\n    Subscribe to a message stream. Returns a subscription object which\n    may be deleted to unsubscribe.\n\n    Arguments:\n\n    channel  -- channel to subscribe to\n    type     -- types to subscribe to, as comma-separated wildcard patterns\n    sender   -- senders to subscribe to, as comma-separated wildcard patterns\n    callback -- message callback with (channel, type, sender, msg, *args) prototype\n    *args    -- optional callback arguments\n    ", /*tp_doc*/
  __pyx_tp_traverse_5evmsg_subscribe, /*tp_traverse*/
  __pyx_tp_clear_5evmsg_subscribe, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5evmsg_subscribe, /*tp_methods*/
  __pyx_members_5evmsg_subscribe, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5evmsg_9subscribe___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5evmsg_subscribe, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"open", (PyCFunction)__pyx_f_5evmsg_open, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5evmsg_open},
  {"set_auth", (PyCFunction)__pyx_f_5evmsg_set_auth, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5evmsg_set_auth},
  {"publish", (PyCFunction)__pyx_f_5evmsg_publish, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5evmsg_publish},
  {"close", (PyCFunction)__pyx_f_5evmsg_close, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5evmsg_close},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initevmsg(void); /*proto*/
PyMODINIT_FUNC initevmsg(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("evmsg", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;};
  __pyx_type_5evmsg_subscribe.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_5evmsg_subscribe) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "subscribe", (PyObject *)&__pyx_type_5evmsg_subscribe) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_ptype_5evmsg_subscribe = &__pyx_type_5evmsg_subscribe;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":17 */
  __pyx_1 = PyInt_FromLong(8888); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_EVMSG_DEFAULT_PORT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":18 */
  __pyx_1 = PyInt_FromLong(4444); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_EVMSG_DEFAULT_SSL_PORT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":44 */
  Py_INCREF(Py_None);
  __pyx_k1 = Py_None;
  Py_INCREF(Py_None);
  __pyx_k2 = Py_None;
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_False); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_k3 = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/dugsong/projects/msgbus/python/evmsg.pyx":94 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("evmsg");
}

static char *__pyx_filenames[] = {
  "evmsg.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2)
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_Size(*args));
        if (!*args2)
            goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (kwds2) {
        if (*kwds) {
            char **p;
            kwds1 = PyDict_New();
            if (!kwds)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (p = kwd_list; *p; p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    Py_XDECREF(*args2);
    Py_XDECREF(*kwds2);
    return -1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
